version: "3.9"

services:
  app:
    build: .
    restart: always
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - log_volume:/app/logs
    env_file:
      - .env
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/static
      - media_volume:/media
    ports:
      - "80:80"
    depends_on:
      - app

  db:
    image: postgres:14-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  redis:
    image: redis:6-alpine
    container_name: redis
    restart: always

volumes:
  static_volume:
  media_volume:
  log_volume:
  postgres_data: